#
# Default Configuration YAML for metaLogger
#
logger:
  auth_key: # api authorization key
  endpoint: # api logger endpoint
  single: # single result log path
  ip: # ip result log path

log:
  ip:
    version: # The version of the IP parser for the correct distribution of linux being used
    mask: # Ip mask to apply to the internal IP address to remove loopbacks, docker networks, or VM networks

  # optional, report the drive empty space left
  #drive:
  #  - { name: "", path: "" }
  # optional, report the last file access time for the path provided
  #file_access:
  #  - { name: "", path: "" }
  # optional, report the file count for the path provided
  #file_count:
  #  - { name: "", path: "" }